# Generated by Django 4.1.7 on 2023-03-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreshBiteApp', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
