# Generated by Django 4.1.7 on 2023-04-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreshBiteApp', '0004_categorydetails_productdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoryDetails',
            new_name='categoryDetail',
        ),
        migrations.RenameModel(
            old_name='productDetails',
            new_name='productDetail',
        ),
    ]
