# Generated by Django 4.1.7 on 2023-04-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreshBiteApp', '0006_cartdetail_rename_is_marketplace_user_is_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='productQuantity',
            field=models.IntegerField(),
        ),
    ]
