# Generated by Django 4.1.7 on 2023-07-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreshBiteApp', '0007_alter_cartdetail_productquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderDetail',
            fields=[
                ('orderId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('orderDate', models.IntegerField()),
                ('orderBy', models.CharField(max_length=36)),
                ('orderTo', models.CharField(max_length=36)),
                ('orderCartValue', models.IntegerField()),
            ],
        ),
    ]
